import React, { useState, useCallback, useEffect, useMemo, useRef } from 'react';
import { HashRouter, Routes, Route, Link, useLocation, Navigate } from 'react-router-dom';
import { DropZone } from './components/DropZone';
import { Visualizer } from './components/Visualizer';
import { DiagnosticPanel } from './components/DiagnosticPanel';
import { AnnotatedCodeView } from './components/AnnotatedCodeView';
import { DiffView } from './components/DiffView';
import { FileEntry, Diagnostic, BundleStats, LintIssue } from './types';
import { analyzeBundleWithGemini, lintBundleWithGemini, refactorBundleWithGemini } from './services/geminiService';
import { 
  Zap, Download, Copy, Trash2, LayoutTemplate, 
  Activity, Sparkles, Code, FileText, Settings, Play,
  FileJson, Palette, File as FileGeneric, Braces, AlignLeft,
  Bug, AlertTriangle, Check, Info as InfoIcon, FileCode2,
  Globe, Paintbrush, RotateCw, GitCompare
} from 'lucide-react';

const STORAGE_KEY_CODE = 'bundle_blitz_code';
const STORAGE_KEY_FILES = 'bundle_blitz_files';
const STORAGE_KEY_SETTINGS = 'bundle_blitz_settings';

const getFileTypeInfo = (fileName: string) => {
  const ext = fileName.split('.').pop()?.toLowerCase();
  switch (ext) {
    case 'js':
    case 'jsx':
    case 'ts':
    case 'tsx':
    case 'mjs':
      return { Icon: FileCode2, color: 'text-yellow-400', bg: 'bg-yellow-400/10', label: 'JavaScript' };
    case 'css':
    case 'scss':
    case 'less':
    case 'sass':
      return { Icon: Paintbrush, color: 'text-blue-400', bg: 'bg-blue-400/10', label: 'Style' };
    case 'html':
    case 'htm':
      return { Icon: Globe, color: 'text-orange-400', bg: 'bg-orange-400/10', label: 'HTML' };
    case 'json':
      return { Icon: FileJson, color: 'text-emerald-400', bg: 'bg-emerald-400/10', label: 'JSON Data' };
    case 'md':
      return { Icon: FileText, color: 'text-pink-400', bg: 'bg-pink-400/10', label: 'Markdown' };
    case 'txt':
      return { Icon: AlignLeft, color: 'text-gray-400', bg: 'bg-gray-400/10', label: 'Plain Text' };
    case 'csv':
      return { Icon: FileText, color: 'text-green-300', bg: 'bg-green-300/10', label: 'CSV Data' };
    default:
      return { Icon: FileGeneric, color: 'text-gray-500', bg: 'bg-gray-500/10', label: ext?.toUpperCase() || 'FILE' };
  }
};

const constructPreview = (files: FileEntry[]) => {
  const htmlFile = files.find(f => /\.(html|htm)$/i.test(f.name));
  const cssFiles = files.filter(f => /\.(css|scss|less)$/i.test(f.name));
  const jsFiles = files.filter(f => /\.(js|ts|jsx|tsx)$/i.test(f.name));

  // Determine base HTML structure
  let html = htmlFile ? htmlFile.content : `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Preview generated by BundleBlitz">
  <title>BundleBlitz Preview</title>
  <style>
    /* Reset & Base Styles */
    html, body { margin: 0; padding: 0; width: 100%; height: 100%; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background-color: #ffffff;
    }
    *, *::before, *::after { box-sizing: border-box; }

    /* Standard Root Containers */
    #root, #app { width: 100%; height: 100%; }

    /* Bundle Loader Overlay */
    .bundle-loader {
      position: fixed; inset: 0;
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      background: #f9fafb; z-index: 10000;
      transition: opacity 0.4s ease-out;
    }
    .bundle-loader h1 {
      color: #2563eb; font-size: 1.5rem; margin-bottom: 1rem;
      font-weight: 600; letter-spacing: -0.025em;
    }
    .spinner {
      width: 32px; height: 32px;
      border: 3px solid #e5e7eb; border-top-color: #2563eb;
      border-radius: 50%; animation: spin 0.8s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }
  </style>
</head>
<body>
  <div id="root"></div>
  <div id="app"></div>
  ${jsFiles.length > 0 && !htmlFile ? `
  <div id="bundle-loader" class="bundle-loader">
    <h1>BundleBlitz Preview</h1>
    <div class="spinner"></div>
  </div>
  <script>
    (function() {
      const loader = document.getElementById('bundle-loader');
      const hideLoader = () => {
        if (loader) {
          loader.style.opacity = '0';
          setTimeout(() => loader.remove(), 400);
        }
      };

      // Detect when content is mounted to root containers
      const observer = new MutationObserver(() => {
        const root = document.getElementById('root');
        const app = document.getElementById('app');
        if ((root && root.innerHTML.trim()) || (app && app.innerHTML.trim())) {
          hideLoader();
          observer.disconnect();
        }
      });
      observer.observe(document.body, { childList: true, subtree: true });

      // Fallback timeout to ensure loader doesn't stick forever
      setTimeout(hideLoader, 2000);
    })();
  </script>` : ''}
</body>
</html>`;

  // Inject CSS
  if (cssFiles.length) {
    const styles = cssFiles.map(f => f.content).join('\n');
    if (html.toLowerCase().includes('</head>')) {
      html = html.replace(/<\/head>/i, `<style>\n/* --- BundleBlitz Styles --- */\n${styles}\n</style>\n</head>`);
    } else {
      html += `<style>\n${styles}\n</style>`;
    }
  }

  // Inject JS
  if (jsFiles.length) {
    const scripts = jsFiles.map(f => f.content).join('\n');
    // Escape closing script tags to prevent breaking the generated HTML
    const safeScripts = scripts.replace(/<\/script>/g, '<\\/script>');
    const scriptBlock = `<script type="module">\n/* --- BundleBlitz Scripts --- */\n${safeScripts}\n</script>`;
    
    if (html.toLowerCase().includes('</body>')) {
      html = html.replace(/<\/body>/i, `${scriptBlock}\n</body>`);
    } else {
      html += scriptBlock;
    }
  }

  return html;
};

type BundleType = 'JS' | 'HTML';

const BundleBlitz: React.FC = () => {
  const location = useLocation();
  const [files, setFiles] = useState<FileEntry[]>([]);
  const [bundledCode, setBundledCode] = useState<string>('');
  const [diagnostics, setDiagnostics] = useState<Diagnostic[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  
  // AI State
  const [aiAnalysis, setAiAnalysis] = useState<string>('');
  const [renderedAnalysis, setRenderedAnalysis] = useState<string>('');
  const [lintIssues, setLintIssues] = useState<LintIssue[]>([]);
  const [refactoredCode, setRefactoredCode] = useState<string>('');
  const [activeAiTab, setActiveAiTab] = useState<'analysis' | 'lint' | 'refactor'>('analysis');
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [isLintLoading, setIsLintLoading] = useState(false);
  const [isRefactoring, setIsRefactoring] = useState(false);
  const [selectedLintIssue, setSelectedLintIssue] = useState<number | null>(null);
  const [refactorInstruction, setRefactorInstruction] = useState('Optimize and clean up this code.');

  const [bundleType, setBundleType] = useState<BundleType>('JS');
  const [enableTranspilation, setEnableTranspilation] = useState(true);
  const [enableFormatting, setEnableFormatting] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  // Auto-save refs
  const filesRef = useRef(files);
  const bundledCodeRef = useRef(bundledCode);
  const lastSavedFilesRef = useRef<string>('');
  const lastSavedCodeRef = useRef<string>('');

  const addDiagnostic = (message: string, type: Diagnostic['type'] = 'info') => {
    setDiagnostics(prev => [...prev, {
      id: Math.random().toString(36).substr(2, 9),
      type,
      message,
      timestamp: Date.now()
    }]);
  };

  // Sync state to refs for auto-save
  useEffect(() => {
    filesRef.current = files;
    bundledCodeRef.current = bundledCode;
  }, [files, bundledCode]);

  // Restore state from LocalStorage on mount
  useEffect(() => {
    const savedCode = localStorage.getItem(STORAGE_KEY_CODE);
    const savedFiles = localStorage.getItem(STORAGE_KEY_FILES);
    const savedSettings = localStorage.getItem(STORAGE_KEY_SETTINGS);
    
    let restoredCount = 0;

    if (savedFiles) {
      try {
        const parsedFiles = JSON.parse(savedFiles);
        if (Array.isArray(parsedFiles) && parsedFiles.length > 0) {
          setFiles(parsedFiles);
          lastSavedFilesRef.current = savedFiles; // Sync for auto-save
          restoredCount = parsedFiles.length;
        }
      } catch (e) {
        console.error('Failed to parse saved files', e);
      }
    }

    if (savedCode) {
      setBundledCode(savedCode);
      lastSavedCodeRef.current = savedCode; // Sync for auto-save
    }
    
    if (savedSettings) {
      try {
        const parsedSettings = JSON.parse(savedSettings);
        if (parsedSettings.bundleType) setBundleType(parsedSettings.bundleType);
        if (parsedSettings.enableTranspilation !== undefined) setEnableTranspilation(parsedSettings.enableTranspilation);
        if (parsedSettings.enableFormatting !== undefined) setEnableFormatting(parsedSettings.enableFormatting);
      } catch (e) {
        console.error('Failed to parse saved settings', e);
      }
    }

    if (restoredCount > 0 || savedCode) {
      addDiagnostic(`Restored previous session: ${restoredCount} files and bundled output loaded.`, 'info');
    }
  }, []);

  // Save settings whenever they change
  useEffect(() => {
    const settings = {
      bundleType,
      enableTranspilation,
      enableFormatting
    };
    localStorage.setItem(STORAGE_KEY_SETTINGS, JSON.stringify(settings));
  }, [bundleType, enableTranspilation, enableFormatting]);

  // Auto-save Interval (every 30 seconds)
  useEffect(() => {
    const intervalId = setInterval(() => {
      const currentFiles = filesRef.current;
      const currentCode = bundledCodeRef.current;
      
      let filesStr = '';
      try {
        filesStr = JSON.stringify(currentFiles);
      } catch(e) {
        console.warn('Failed to stringify files for auto-save', e);
        return;
      }

      const filesChanged = filesStr !== lastSavedFilesRef.current;
      const codeChanged = currentCode !== lastSavedCodeRef.current;

      if (filesChanged || codeChanged) {
        try {
          if (filesChanged && currentFiles.length > 0) {
            localStorage.setItem(STORAGE_KEY_FILES, filesStr);
            lastSavedFilesRef.current = filesStr;
          }
          if (codeChanged && currentCode) {
            localStorage.setItem(STORAGE_KEY_CODE, currentCode);
            lastSavedCodeRef.current = currentCode;
          }
        } catch (e) {
          console.warn('Auto-save failed: quota exceeded');
        }
      }
    }, 30000); // 30 seconds

    return () => clearInterval(intervalId);
  }, []);

  // Update preview URL when switching to preview tab or files change
  useEffect(() => {
    if (location.pathname === '/preview') {
      const html = constructPreview(files);
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      setPreviewUrl(url);

      // Cleanup
      return () => URL.revokeObjectURL(url);
    }
  }, [files, location.pathname]);

  // Render Markdown for AI Analysis
  useEffect(() => {
    if (!aiAnalysis) return;
    const renderMarkdown = async () => {
      try {
        // @ts-ignore
        const markedMod = await import('marked');
        const parse = markedMod.parse || markedMod.marked?.parse || markedMod.default?.parse;
        if (parse) {
          const html = await parse(aiAnalysis);
          setRenderedAnalysis(html);
        } else {
          setRenderedAnalysis(aiAnalysis); // Fallback
        }
      } catch (e) {
        console.error('Failed to load marked', e);
        setRenderedAnalysis(aiAnalysis);
      }
    };
    renderMarkdown();
  }, [aiAnalysis]);

  const handleFilesSelected = async (selectedFiles: File[]) => {
    setIsProcessing(true);
    const newFileEntries: FileEntry[] = [];
    let hasHtml = false;
    
    try {
      for (const file of selectedFiles) {
        const text = await file.text();
        const ext = file.name.split('.').pop()?.toLowerCase();

        // Type specific checks & diagnostics
        if (ext === 'json') {
          try {
            JSON.parse(text);
          } catch (e) {
            addDiagnostic(`Invalid JSON syntax in ${file.name}`, 'error');
          }
        } else if (ext === 'md') {
          if (text.trim().length === 0) {
            addDiagnostic(`Markdown file ${file.name} is empty`, 'warning');
          } else if (!text.includes('#')) {
            addDiagnostic(`Markdown file ${file.name} missing headers (#) - consider structuring content`, 'info');
          }
        } else if (ext === 'txt') {
          if (text.trim().length === 0) {
             addDiagnostic(`Text file ${file.name} is empty`, 'warning');
          }
        } else if (ext === 'html' || ext === 'htm') {
           hasHtml = true;
        } else if (['css', 'scss', 'less'].includes(ext || '')) {
           if (text.includes('@import')) {
             addDiagnostic(`Performance warning: @import found in ${file.name}`, 'warning');
           }
        } else if (['js', 'ts', 'jsx', 'tsx'].includes(ext || '')) {
          if (text.includes('eval(')) {
            addDiagnostic(`Security Warning: 'eval' usage detected in ${file.name}`, 'warning');
          }
        }

        newFileEntries.push({
          id: Math.random().toString(36).substr(2, 9),
          name: file.name,
          size: file.size,
          content: text,
          type: file.type
        });
      }
      
      setFiles(prev => [...prev, ...newFileEntries]);
      
      // Auto-switch to HTML mode if user drops an HTML file
      if (hasHtml) {
        setBundleType('HTML');
        addDiagnostic('HTML file detected. Switched to HTML Bundle mode.', 'info');
      }

      addDiagnostic(`Successfully loaded ${selectedFiles.length} file(s).`, 'info');
    } catch (err) {
      addDiagnostic('Failed to read one or more files.', 'error');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleBundle = useCallback(async () => {
    if (files.length === 0) {
      addDiagnostic('No files to bundle.', 'warning');
      return;
    }

    setIsProcessing(true);
    
    // Allow UI to update to "processing" state
    await new Promise(resolve => setTimeout(resolve, 100));

    try {
      let finalCode = '';

      if (bundleType === 'HTML') {
        // --- HTML BUNDLER ---
        addDiagnostic('Generating Single-File HTML Bundle...', 'info');
        finalCode = constructPreview(files);
      } else {
        // --- JS BUNDLER ---
        const header = `/**\n * BundleBlitz ⚡\n * Generated: ${new Date().toISOString()}\n * Files: ${files.length}\n */\n\n`;
        
        let content = files.map(f => {
          const ext = f.name.split('.').pop()?.toLowerCase();
          const isScript = ['js', 'ts', 'jsx', 'tsx'].includes(ext || '');
          
          let fileContent = f.content;
          
          if (!isScript) {
            const safeContent = f.content.replace(/\*\//g, '* /');
            fileContent = `/*\n[Non-Script File: ${f.name}]\n\n${safeContent}\n*/`;
          }

          return `// --- BEGIN ${f.name} (${f.size} bytes) ---\n${fileContent}\n// --- END ${f.name} ---\n`;
        }).join('\n');
        
        finalCode = header + content;

        // 1. Transpilation (Babel)
        if (enableTranspilation) {
          addDiagnostic('Loading Babel for transpilation...', 'info');
          try {
            // @ts-ignore
            const Babel = await import('@babel/standalone');
            const transformFn = Babel.transform || (Babel as any).default?.transform;

            if (transformFn) {
              const result = transformFn(finalCode, {
                presets: ['env'],
                filename: 'bundle.js',
                retainLines: true,
              });
              
              if (result.code) {
                finalCode = result.code;
                addDiagnostic('Transpilation to ES5 successful.', 'info');
              }
            }
          } catch (babelError: any) {
            console.error(babelError);
            addDiagnostic(`Transpilation warning: ${babelError.message}`, 'warning');
          }
        }
      }

      // 2. Formatting (Prettier) - Only for JS currently
      if (enableFormatting && bundleType === 'JS') {
        addDiagnostic('Formatting code with Prettier...', 'info');
        try {
          // @ts-ignore
          const prettier = await import('prettier');
          // @ts-ignore
          const parserBabelMod = await import('prettier/plugins/babel');
          // @ts-ignore
          const parserEstreeMod = await import('prettier/plugins/estree');
          
          const prettierFormat = prettier.format || (prettier as any).default?.format;
          const parserBabel = parserBabelMod.default || parserBabelMod;
          const parserEstree = parserEstreeMod.default || parserEstreeMod;

          if (prettierFormat) {
             finalCode = await prettierFormat(finalCode, {
              parser: 'babel',
              plugins: [parserBabel, parserEstree],
              semi: true,
              singleQuote: true,
              printWidth: 80,
            });
            addDiagnostic('Code formatted successfully.', 'info');
          }
        } catch (fmtError: any) {
          console.error(fmtError);
          addDiagnostic(`Formatting failed: ${fmtError.message}`, 'warning');
        }
      }
      
      setBundledCode(finalCode);
      addDiagnostic(`Bundle created successfully! Size: ${finalCode.length} bytes.`, 'info');
      
      // Clear previous analysis/refactor state
      setAiAnalysis('');
      setRenderedAnalysis('');
      setLintIssues([]);
      setRefactoredCode('');
      setSelectedLintIssue(null);

      try {
        const filesStr = JSON.stringify(files);
        localStorage.setItem(STORAGE_KEY_CODE, finalCode);
        localStorage.setItem(STORAGE_KEY_FILES, filesStr);
        // Sync refs for auto-saver to know we just saved
        lastSavedCodeRef.current = finalCode;
        lastSavedFilesRef.current = filesStr;
      } catch (e) {
        addDiagnostic('Auto-save failed: Storage quota exceeded.', 'warning');
      }

    } catch (err) {
      console.error(err);
      addDiagnostic('Error during bundling process.', 'error');
    } finally {
      setIsProcessing(false);
    }
  }, [files, enableTranspilation, enableFormatting, bundleType]);

  const handleDownload = () => {
    if (!bundledCode) return;
    const isHtml = bundleType === 'HTML';
    const blob = new Blob([bundledCode], { type: isHtml ? 'text/html' : 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = isHtml ? 'index.html' : 'bundle.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    addDiagnostic(`Download started (${a.download}).`, 'info');
  };

  const handleCopy = () => {
    if (!bundledCode) return;
    navigator.clipboard.writeText(bundledCode)
      .then(() => addDiagnostic('Bundled code copied to clipboard.', 'info'))
      .catch(() => addDiagnostic('Failed to copy to clipboard.', 'error'));
  };

  const handleClear = () => {
    setFiles([]);
    setBundledCode('');
    setDiagnostics([]);
    setAiAnalysis('');
    setRenderedAnalysis('');
    setLintIssues([]);
    setRefactoredCode('');
    setSelectedLintIssue(null);
    localStorage.removeItem(STORAGE_KEY_CODE);
    localStorage.removeItem(STORAGE_KEY_FILES);
    localStorage.removeItem(STORAGE_KEY_SETTINGS);
    
    // Clear auto-save refs
    lastSavedFilesRef.current = '';
    lastSavedCodeRef.current = '';
    
    addDiagnostic('Workspace cleared.', 'info');
  };

  const handleAiAnalyze = async () => {
    if (!bundledCode) {
      addDiagnostic('Please bundle files before running AI analysis.', 'warning');
      return;
    }
    setActiveAiTab('analysis');
    setIsAiLoading(true);
    try {
      const result = await analyzeBundleWithGemini(bundledCode);
      setAiAnalysis(result);
      addDiagnostic('AI Analysis completed.', 'info');
    } catch (error) {
      addDiagnostic('AI Analysis failed. Check API configuration.', 'error');
      setAiAnalysis('Analysis failed. Please ensure the API Key is configured correctly in the environment.');
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleAiLint = async () => {
    if (!bundledCode) {
      addDiagnostic('Please bundle files before running AI Linter.', 'warning');
      return;
    }
    setActiveAiTab('lint');
    setIsLintLoading(true);
    setSelectedLintIssue(null);
    try {
      const issues = await lintBundleWithGemini(bundledCode);
      setLintIssues(issues);
      addDiagnostic(`AI Linting completed. Found ${issues.length} issues.`, 'info');
    } catch (error) {
      addDiagnostic('AI Linting failed. Check API configuration.', 'error');
    } finally {
      setIsLintLoading(false);
    }
  };

  const handleAiRefactor = async () => {
    if (!bundledCode) {
      addDiagnostic('Please bundle files before running AI Refactoring.', 'warning');
      return;
    }
    setActiveAiTab('refactor');
    setIsRefactoring(true);
    try {
      const result = await refactorBundleWithGemini(bundledCode, refactorInstruction);
      setRefactoredCode(result);
      addDiagnostic('AI Refactoring completed. Check the diff view.', 'info');
    } catch (error) {
      addDiagnostic('AI Refactoring failed. Check API configuration.', 'error');
    } finally {
      setIsRefactoring(false);
    }
  };

  const handleApplyRefactor = () => {
    if (!refactoredCode) return;
    setBundledCode(refactoredCode);
    setRefactoredCode('');
    // Save to storage
    localStorage.setItem(STORAGE_KEY_CODE, refactoredCode);
    lastSavedCodeRef.current = refactoredCode;
    addDiagnostic('Refactored code applied successfully.', 'info');
    setActiveAiTab('analysis'); // Reset tab or go to editor
  };

  const stats: BundleStats = {
    fileCount: files.length,
    totalSize: files.reduce((acc, f) => acc + f.size, 0),
    linesOfCode: bundledCode.split('\n').length
  };

  const activePath = location.pathname;

  return (
    <div className="min-h-screen pb-20 relative overflow-hidden">
      {/* Background Decor */}
      <div className="fixed top-0 left-0 w-full h-full pointer-events-none z-0">
         <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-neon-cyan/5 rounded-full blur-[100px]" />
         <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-neon-magenta/5 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <header className="mb-10 flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
          <div>
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-2 flex items-center gap-3">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-neon-cyan to-neon-magenta animate-pulse-fast">
                BundleBlitz
              </span>
              <Zap className="text-neon-cyan fill-current" size={40} />
            </h1>
            <p className="text-gray-400 text-lg max-w-2xl">
              High-performance single-file bundler. Drag a folder to create a static site instantly.
            </p>
          </div>
          
          <div className="flex gap-4">
            <div className="bg-dark-card border border-white/10 px-4 py-2 rounded-lg text-sm">
              <span className="block text-gray-500 text-xs uppercase font-bold">Files</span>
              <span className="text-white font-mono text-xl">{stats.fileCount}</span>
            </div>
            <div className="bg-dark-card border border-white/10 px-4 py-2 rounded-lg text-sm">
              <span className="block text-gray-500 text-xs uppercase font-bold">Size</span>
              <span className="text-neon-cyan font-mono text-xl">
                {(stats.totalSize / 1024).toFixed(2)} KB
              </span>
            </div>
          </div>
        </header>

        {/* Main Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Left Column: Input & Controls */}
          <div className="lg:col-span-4 space-y-6">
            <DropZone onFilesSelected={handleFilesSelected} />

            {/* File List */}
            {files.length > 0 && (
              <div className="bg-dark-card border border-white/10 rounded-xl overflow-hidden">
                <div className="p-4 border-b border-white/10 flex justify-between items-center">
                  <h3 className="font-bold text-gray-200">Selected Files</h3>
                  <span className="text-xs text-gray-500 font-mono">{files.length} items</span>
                </div>
                <div className="max-h-60 overflow-y-auto custom-scrollbar">
                  {files.map((f, i) => {
                    const { Icon, color, bg, label } = getFileTypeInfo(f.name);
                    return (
                      <div key={f.id} className="px-4 py-3 border-b border-white/5 flex justify-between items-center hover:bg-white/5 transition-colors group">
                        <div className="flex items-center gap-3 overflow-hidden">
                          <div className={`p-2 rounded-lg ${bg} ${color} shrink-0`}>
                            <Icon size={18} />
                          </div>
                          <div className="flex flex-col min-w-0">
                             <span className="text-sm text-gray-200 font-medium truncate group-hover:text-white transition-colors">{f.name}</span>
                             <span className="text-[10px] text-gray-500 font-mono uppercase tracking-wider">{label}</span>
                          </div>
                        </div>
                        <span className="text-xs text-gray-500 font-mono shrink-0">{(f.size / 1024).toFixed(1)}KB</span>
                      </div>
                    );
                  })}
                </div>
                <div className="p-4 bg-white/5 flex flex-col gap-3">
                  
                  {/* Build Configuration */}
                  <div className="mb-2 px-1">
                    <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Build Configuration</h4>
                    <div className="space-y-3">
                      
                      {/* Bundle Type Toggle */}
                      <div className="flex bg-gray-800 rounded-lg p-1 border border-white/10 mb-4">
                        <button
                          onClick={() => setBundleType('JS')}
                          className={`flex-1 flex items-center justify-center gap-2 py-1.5 rounded-md text-xs font-bold transition-all ${bundleType === 'JS' ? 'bg-white/10 text-white shadow' : 'text-gray-400 hover:text-white'}`}
                        >
                           <FileCode2 size={14} /> JS Bundle
                        </button>
                        <button
                          onClick={() => setBundleType('HTML')}
                          className={`flex-1 flex items-center justify-center gap-2 py-1.5 rounded-md text-xs font-bold transition-all ${bundleType === 'HTML' ? 'bg-orange-500/20 text-orange-400 shadow border border-orange-500/30' : 'text-gray-400 hover:text-white'}`}
                        >
                           <LayoutTemplate size={14} /> HTML Bundle
                        </button>
                      </div>

                      {bundleType === 'JS' && (
                        <>
                          {/* Transpilation Toggle */}
                          <label className="flex items-center gap-3 cursor-pointer group select-none">
                            <div className="relative">
                              <input 
                                type="checkbox" 
                                checked={enableTranspilation}
                                onChange={(e) => setEnableTranspilation(e.target.checked)}
                                className="sr-only peer" 
                              />
                              <div className="w-11 h-6 bg-gray-700 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-neon-cyan"></div>
                            </div>
                            <span className="text-sm text-gray-300 flex items-center gap-2 group-hover:text-white transition-colors">
                              <Settings size={16} className="text-neon-cyan" />
                              <div>
                                <span className="block font-medium">Transpile to ES5</span>
                                <span className="block text-xs text-gray-500">Use Babel for compatibility</span>
                              </div>
                            </span>
                          </label>

                          {/* Formatting Toggle */}
                          <label className="flex items-center gap-3 cursor-pointer group select-none">
                            <div className="relative">
                              <input 
                                type="checkbox" 
                                checked={enableFormatting}
                                onChange={(e) => setEnableFormatting(e.target.checked)}
                                className="sr-only peer" 
                              />
                              <div className="w-11 h-6 bg-gray-700 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-neon-magenta"></div>
                            </div>
                            <span className="text-sm text-gray-300 flex items-center gap-2 group-hover:text-white transition-colors">
                              <AlignLeft size={16} className="text-neon-magenta" />
                              <div>
                                <span className="block font-medium">Format Code (Prettier)</span>
                                <span className="block text-xs text-gray-500">Format JS output</span>
                              </div>
                            </span>
                          </label>
                        </>
                      )}
                      
                      {bundleType === 'HTML' && (
                        <div className="p-3 bg-orange-500/5 border border-orange-500/20 rounded-lg">
                          <p className="text-xs text-orange-300 flex items-start gap-2">
                            <InfoIcon size={14} className="mt-0.5 shrink-0" />
                            Generates a single index.html file with all CSS and JS inlined.
                          </p>
                        </div>
                      )}
                    </div>
                  </div>
                  
                  <div className="border-t border-white/10 my-1"></div>

                  <button
                    onClick={handleBundle}
                    disabled={isProcessing || files.length === 0}
                    className="w-full py-3 rounded-lg bg-gradient-to-r from-neon-cyan to-neon-purple text-dark-bg font-bold hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg shadow-neon-cyan/20"
                  >
                    {isProcessing ? <Activity className="animate-spin" size={20} /> : <Zap size={20} />}
                    {bundleType === 'HTML' ? 'Generate HTML' : 'Bundle Files'}
                  </button>
                  <button
                    onClick={handleClear}
                    className="w-full py-3 rounded-lg border border-white/10 text-gray-400 hover:text-white hover:border-white/30 transition-all flex items-center justify-center gap-2"
                  >
                    <Trash2 size={18} />
                    Clear Workspace
                  </button>
                </div>
              </div>
            )}

            <DiagnosticPanel diagnostics={diagnostics} onDismiss={(id) => setDiagnostics(prev => prev.filter(d => d.id !== id))} />
          </div>

          {/* Right Column: Output & Tools */}
          <div className="lg:col-span-8 flex flex-col gap-6">
            {/* Tabs */}
            <div className="flex items-center gap-2 p-1 bg-dark-card border border-white/10 rounded-xl w-fit">
              {[
                { path: '/editor', label: 'Code Editor', icon: Code },
                { path: '/visualizer', label: 'Visualizer', icon: LayoutTemplate },
                { path: '/ai-insights', label: 'AI Insights', icon: Sparkles },
                { path: '/preview', label: 'Live Preview', icon: Play },
              ].map(tab => (
                <Link
                  key={tab.path}
                  to={tab.path}
                  className={`
                    flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all
                    ${activePath === tab.path 
                      ? 'bg-white/10 text-neon-cyan shadow-sm' 
                      : 'text-gray-400 hover:text-white hover:bg-white/5'}
                  `}
                >
                  <tab.icon size={16} />
                  {tab.label}
                </Link>
              ))}
            </div>

            {/* Content Area */}
            <div className="flex-1 min-h-[500px] bg-dark-card border border-white/10 rounded-xl overflow-hidden relative shadow-2xl">
              <Routes>
                <Route path="/" element={<Navigate to="/editor" replace />} />
                
                {/* Editor View */}
                <Route path="/editor" element={
                  <div className="h-full flex flex-col">
                    <div className="flex justify-between items-center p-4 border-b border-white/10 bg-white/5">
                      <span className="text-gray-400 text-sm font-mono flex items-center gap-2">
                        {bundleType === 'HTML' ? 'index.html' : 'bundle.js'}
                        {enableTranspilation && bundleType === 'JS' && <span className="text-xs bg-neon-cyan/10 text-neon-cyan px-2 py-0.5 rounded border border-neon-cyan/20">ES5</span>}
                        {enableFormatting && bundleType === 'JS' && <span className="text-xs bg-neon-magenta/10 text-neon-magenta px-2 py-0.5 rounded border border-neon-magenta/20">Prettier</span>}
                      </span>
                      <div className="flex gap-2">
                        <button 
                          onClick={handleCopy}
                          disabled={!bundledCode}
                          className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-neon-cyan transition-colors disabled:opacity-50"
                          title="Copy Code"
                        >
                          <Copy size={18} />
                        </button>
                        <button 
                          onClick={handleDownload}
                          disabled={!bundledCode}
                          className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-neon-cyan transition-colors disabled:opacity-50"
                          title="Download Bundle"
                        >
                          <Download size={18} />
                        </button>
                      </div>
                    </div>
                    <textarea 
                      value={bundledCode} 
                      readOnly 
                      placeholder="// Bundled code will appear here..."
                      className="flex-1 w-full bg-dark-bg p-4 font-mono text-sm text-gray-300 focus:outline-none resize-none"
                    />
                  </div>
                } />

                {/* Visualizer View */}
                <Route path="/visualizer" element={
                  <div className="h-full p-6 overflow-y-auto">
                    <Visualizer files={files} />
                  </div>
                } />

                {/* AI Insights View */}
                <Route path="/ai-insights" element={
                  <div className="h-full p-6 flex flex-col">
                    {!bundledCode ? (
                      <div className="flex-1 flex flex-col items-center justify-center text-gray-500 gap-4">
                         <Code size={48} className="opacity-20" />
                         <p>Bundle your files first to enable AI analysis.</p>
                      </div>
                    ) : (
                      <>
                        <div className="flex justify-between items-center mb-6">
                          <div className="flex items-center gap-4">
                             <h3 className="text-xl font-bold text-white flex items-center gap-2">
                               <Sparkles size={20} className="text-neon-purple" />
                               AI Insights
                             </h3>
                             <div className="flex bg-white/5 rounded-lg p-1 border border-white/10">
                                <button
                                  onClick={() => setActiveAiTab('analysis')}
                                  className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${activeAiTab === 'analysis' ? 'bg-neon-purple text-white shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                  Deep Analysis
                                </button>
                                <button
                                  onClick={() => setActiveAiTab('lint')}
                                  className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${activeAiTab === 'lint' ? 'bg-neon-cyan text-dark-bg shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                  Smart Linter
                                </button>
                                <button
                                  onClick={() => setActiveAiTab('refactor')}
                                  className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${activeAiTab === 'refactor' ? 'bg-green-500 text-white shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                  Auto-Refactor
                                </button>
                             </div>
                          </div>
                          
                          {activeAiTab === 'analysis' ? (
                            <button
                              onClick={handleAiAnalyze}
                              disabled={isAiLoading}
                              className="px-4 py-2 bg-neon-purple/20 text-neon-purple border border-neon-purple/50 rounded-lg hover:bg-neon-purple/30 transition-all flex items-center gap-2 text-sm font-bold"
                            >
                              {isAiLoading ? <Activity className="animate-spin" size={16} /> : <Sparkles size={16} />}
                              {aiAnalysis ? 'Re-Analyze' : 'Run Analysis'}
                            </button>
                          ) : activeAiTab === 'lint' ? (
                            <button
                              onClick={handleAiLint}
                              disabled={isLintLoading}
                              className="px-4 py-2 bg-neon-cyan/20 text-neon-cyan border border-neon-cyan/50 rounded-lg hover:bg-neon-cyan/30 transition-all flex items-center gap-2 text-sm font-bold"
                            >
                              {isLintLoading ? <Activity className="animate-spin" size={16} /> : <Bug size={16} />}
                              {lintIssues.length > 0 ? 'Re-Lint' : 'Run Linter'}
                            </button>
                          ) : (
                             // Refactor Tab Controls
                             <div className="flex gap-2">
                               <button
                                onClick={handleAiRefactor}
                                disabled={isRefactoring}
                                className="px-4 py-2 bg-green-500/20 text-green-400 border border-green-500/50 rounded-lg hover:bg-green-500/30 transition-all flex items-center gap-2 text-sm font-bold"
                              >
                                {isRefactoring ? <Activity className="animate-spin" size={16} /> : <RotateCw size={16} />}
                                {refactoredCode ? 'Regenerate' : 'Refactor Code'}
                              </button>
                              {refactoredCode && (
                                <button
                                  onClick={handleApplyRefactor}
                                  className="px-4 py-2 bg-white/10 text-white border border-white/20 rounded-lg hover:bg-white/20 transition-all flex items-center gap-2 text-sm font-bold"
                                >
                                  <Check size={16} /> Apply Changes
                                </button>
                              )}
                             </div>
                          )}
                        </div>
                        
                        <div className="flex-1 bg-dark-bg/50 rounded-xl border border-white/5 overflow-hidden relative">
                          {activeAiTab === 'analysis' ? (
                            <div className="p-6 h-full overflow-y-auto custom-scrollbar">
                              {isAiLoading ? (
                                <div className="space-y-4 animate-pulse">
                                  <div className="h-4 bg-white/10 rounded w-3/4"></div>
                                  <div className="h-4 bg-white/10 rounded w-1/2"></div>
                                  <div className="h-4 bg-white/10 rounded w-5/6"></div>
                                  <div className="text-center pt-8 text-gray-500 text-sm animate-pulse">Analyzing bundle with Gemini...</div>
                                </div>
                              ) : aiAnalysis ? (
                                <div 
                                  className="prose prose-invert prose-sm max-w-none font-sans text-gray-300 leading-relaxed prose-headings:text-neon-cyan prose-a:text-neon-magenta"
                                  dangerouslySetInnerHTML={{ __html: renderedAnalysis }}
                                />
                              ) : (
                                <div className="flex flex-col items-center justify-center h-full text-gray-500 italic text-center">
                                  <Sparkles size={40} className="mb-4 opacity-20" />
                                  <p>Click "Run Analysis" to check for security risks, <br/> bad practices, and performance issues.</p>
                                </div>
                              )}
                            </div>
                          ) : activeAiTab === 'lint' ? (
                            <div className="h-full flex flex-col">
                               {isLintLoading ? (
                                <div className="p-6 space-y-4 animate-pulse">
                                  <div className="h-10 bg-white/10 rounded w-full"></div>
                                  <div className="h-10 bg-white/10 rounded w-full"></div>
                                  <div className="h-10 bg-white/10 rounded w-full"></div>
                                  <div className="text-center pt-8 text-gray-500 text-sm animate-pulse">Linting code with Gemini...</div>
                                </div>
                              ) : lintIssues.length > 0 ? (
                                <div className="flex h-full">
                                  {/* Left Pane: Issue List */}
                                  <div className="w-1/3 border-r border-white/10 overflow-y-auto custom-scrollbar bg-dark-card/50">
                                    <table className="w-full text-left text-sm text-gray-400">
                                      <thead className="bg-white/5 text-gray-200 sticky top-0 backdrop-blur-sm z-10">
                                        <tr>
                                          <th className="p-3 font-semibold text-xs uppercase">Issues ({lintIssues.length})</th>
                                        </tr>
                                      </thead>
                                      <tbody className="divide-y divide-white/5">
                                        {lintIssues.map((issue, idx) => (
                                          <tr 
                                            key={idx} 
                                            onClick={() => setSelectedLintIssue(idx)}
                                            className={`cursor-pointer transition-colors ${selectedLintIssue === idx ? 'bg-white/10' : 'hover:bg-white/5'}`}
                                          >
                                            <td className="p-3">
                                              <div className="flex items-center justify-between mb-1">
                                                {issue.severity === 'error' ? (
                                                  <span className="inline-flex items-center gap-1 text-red-400 text-xs font-bold uppercase">
                                                    <AlertTriangle size={10} /> Error
                                                  </span>
                                                ) : issue.severity === 'warning' ? (
                                                  <span className="inline-flex items-center gap-1 text-yellow-400 text-xs font-bold uppercase">
                                                    <AlertTriangle size={10} /> Warn
                                                  </span>
                                                ) : (
                                                  <span className="inline-flex items-center gap-1 text-blue-400 text-xs font-bold uppercase">
                                                    <InfoIcon size={10} /> Info
                                                  </span>
                                                )}
                                                <span className="font-mono text-xs text-gray-600">L{issue.line || '?'}</span>
                                              </div>
                                              <div className="text-gray-300 line-clamp-2 text-xs mb-1">{issue.message}</div>
                                              {issue.suggestion && (
                                                <div className="text-neon-cyan/60 italic text-[10px] line-clamp-1">Tip: {issue.suggestion}</div>
                                              )}
                                            </td>
                                          </tr>
                                        ))}
                                      </tbody>
                                    </table>
                                  </div>
                                  {/* Right Pane: Annotated Code View */}
                                  <div className="flex-1 h-full overflow-hidden bg-[#1d1f21] relative">
                                    <AnnotatedCodeView 
                                      code={bundledCode} 
                                      issues={lintIssues} 
                                      selectedIssueIndex={selectedLintIssue} 
                                    />
                                  </div>
                                </div>
                              ) : (
                                <div className="flex flex-col items-center justify-center h-full text-gray-500 italic text-center p-6">
                                  <Bug size={40} className="mb-4 opacity-20" />
                                  <p>Click "Run Linter" to check for syntax errors, <br/> bugs, and bad practices.</p>
                                  {lintIssues.length === 0 && !isLintLoading && activeAiTab === 'lint' && (
                                    <p className="mt-2 text-green-500/50 text-xs font-bold flex items-center gap-1 justify-center">
                                      <Check size={14} /> No issues found! Clean code.
                                    </p>
                                  )}
                                </div>
                              )}
                            </div>
                          ) : (
                             // Refactor Tab Content
                             <div className="h-full flex flex-col p-4">
                               {!refactoredCode ? (
                                 <div className="flex flex-col items-center justify-center h-full gap-4">
                                   <div className="w-full max-w-lg space-y-3">
                                      <label className="text-sm text-gray-400 font-bold uppercase tracking-wider">Refactoring Instructions</label>
                                      <textarea 
                                        className="w-full bg-dark-card border border-white/10 rounded-lg p-3 text-gray-300 focus:outline-none focus:border-neon-cyan transition-colors h-32"
                                        placeholder="E.g., 'Convert to ES6 classes', 'Optimize loops', 'Remove unused variables', or 'Clean up this mess!'"
                                        value={refactorInstruction}
                                        onChange={(e) => setRefactorInstruction(e.target.value)}
                                      />
                                      <button
                                        onClick={handleAiRefactor}
                                        disabled={isRefactoring}
                                        className="w-full py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-bold flex items-center justify-center gap-2"
                                      >
                                        {isRefactoring ? <Activity className="animate-spin" /> : <RotateCw />}
                                        Start Refactoring
                                      </button>
                                   </div>
                                 </div>
                               ) : (
                                 <div className="h-full flex flex-col">
                                    <div className="flex justify-between items-center mb-2 px-2">
                                       <div className="flex items-center gap-2 text-gray-400 text-sm">
                                         <GitCompare size={16} />
                                         <span>Diff View: Original vs. Refactored</span>
                                       </div>
                                    </div>
                                    <div className="flex-1 overflow-hidden">
                                       <DiffView original={bundledCode} modified={refactoredCode} />
                                    </div>
                                 </div>
                               )}
                             </div>
                          )}
                        </div>
                      </>
                    )}
                  </div>
                } />

                {/* Preview View */}
                <Route path="/preview" element={
                  <div className="h-full w-full bg-white rounded-xl overflow-hidden relative">
                    {files.length === 0 ? (
                      <div className="h-full flex flex-col items-center justify-center text-gray-500 gap-4 bg-dark-card border-none">
                        <Play size={48} className="opacity-20" />
                        <p>Add files to generate a live preview.</p>
                      </div>
                    ) : (
                      <iframe 
                        src={previewUrl || ''} 
                        className="w-full h-full border-none bg-white"
                        title="Live Preview"
                        sandbox="allow-scripts allow-modals allow-same-origin"
                      />
                    )}
                  </div>
                } />
              </Routes>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  return (
    <HashRouter>
      <BundleBlitz />
    </HashRouter>
  );
};

export default App;